# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MISP² 2026
author:
  email: misp2@lumc.nl
email: misp2@lumc.nl
description: >- # this means to ignore newlines until "baseurl:"
  This is the official site for the Dutch Medical Imaging Symposium for PhDs and Postdocs.

markdown: GFM

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://medimagesymposium.github.io/"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

include:
  - _pages

exclude:
  - .vscode/
  - .sass-cache/
  - .jekyll-cache/
  - README.md
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/